### ISSUE TITLE
Is there a corresponding paper for this code?

### ISSUE THREAD

**Issue by zhangchenlu999** [Aihong-Sun/ACO_for_DRCFJSP#2]

**Comment by Aihong-Sun** [comment]
孙爱红,宋豫川,杨云帆等.考虑关键件加工质量的双资源约束柔性作业车间调度算法[J].中国机械工程,2022.






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Aihong-Sun/ACO_for_DRCFJSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月27日(星期天) 中午11:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Aihong-Sun/ACO_for_DRCFJSP] Is there a corresponding paper for this code? (Issue #2)

**Comment by zhangchenlu999** [comment]
thankyou！

**Comment by Aihong-Sun** [comment]
you are welcome
